-d C:\Users\lpc\Desktop\sipeed_tang_primer_20k\sipeed_tang_primeri_20k\fpga_project\impl\gwsynthesis\fpga_project.vg
-p GW2A-18C-PBGA256-8
-pn GW2A-LV18PG256C8/I7
-cst C:\Users\lpc\Desktop\sipeed_tang_primer_20k\sipeed_tang_primeri_20k\fpga_project\src\sipeed_tang_primer_20k.cst
-cfg C:\Users\lpc\Desktop\sipeed_tang_primer_20k\sipeed_tang_primeri_20k\fpga_project\impl\pnr\device.cfg
-sdc C:\Users\lpc\Desktop\sipeed_tang_primer_20k\sipeed_tang_primeri_20k\fpga_project\src\sipeed_tang_primer_20k.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
